// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCZqiv26b2DsTXy6OlUFpbSp3NvyQ4ok',
    appId: '1:566423133335:web:b83a014858fbe62bb1ddd2',
    messagingSenderId: '566423133335',
    projectId: 'mental-health-care-6aba8',
    authDomain: 'mental-health-care-6aba8.firebaseapp.com',
    storageBucket: 'mental-health-care-6aba8.appspot.com',
    measurementId: 'G-T5NQLSBHX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZv6d91vA93qeFeGPqda70I2dEapboT8',
    appId: '1:566423133335:android:e3db33da285788dcb1ddd2',
    messagingSenderId: '566423133335',
    projectId: 'mental-health-care-6aba8',
    storageBucket: 'mental-health-care-6aba8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANw3ic41KNHKoZCdmF2v3xSY3eHwqFHA4',
    appId: '1:566423133335:ios:dc8c7cac087500e6b1ddd2',
    messagingSenderId: '566423133335',
    projectId: 'mental-health-care-6aba8',
    storageBucket: 'mental-health-care-6aba8.appspot.com',
    iosClientId: '566423133335-iqshs0b1v2gc4g5m42j576ofv8j0c3br.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthCare',
  );
}
